### ISSUE TITLE
Not working yet?

### ISSUE THREAD

**Issue by gaetgu** [tomiy/openrider#10]
Hey guys, I came across this while trying to create an alternate FRHD editor. I downloaded and unzipped the repo, but when I open the `index.html` file, it looks like this:
![Screen Shot 2020-06-09 at 6 13 53 PM](https://user-images.githubusercontent.com/47652746/84213195-409ebc00-aa7d-11ea-823f-ebc091e585dc.png)
I am kind of confused on why this is - I downloaded the `master` branch, so is it still in-dev? If so, I would be willing to help, at least as much as I can. Thanks!

**Comment by tomiy** [comment]
The architecture for this rewrite is based on es6 modules, which don't work locally because of cors, so you have to start up a local webserver to access localhost :)
Also it's kinda dead as of now, need to find motivation to continue deobfuscating/cleaning/etc.

**Comment by gaetgu** [comment]
Alright, so I host it on a web server. I have XAMPP so I can run it on an apache, right? Also, while I am not the best at ES6, I can try to help.
==EDIT==
So I ran it on an apache web server with XAMPP, but it still gave me the same results, with the toolbar on the wrong side and not showing anything else. Is there anything I need to enable/disable?

**Comment by tomiy** [comment]
That's odd, is there anything showing up in the console?

e; tried a fresh copy of master with no problems after booting it up on localhost (using xampp as well). May be a browser specific thing? Still gonna need any console info

**Comment by gaetgu** [comment]
I tried on Safari, Brave, and Chrome, but none worked. I checked the console on Safari and found this:

`SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.`

I have my own personal version that works, I will make a PR if that's fine.

**Comment by tomiy** [comment]
This seems related: https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet
I can't really test for Safari, and I need to test for Firefox, but Chromium based browsers are 100% operational.

**Comment by hornta** [comment]
I'm currently working on open sourcing freerider and I in the middle of the deobfuscation process and I will really need some help with some parts. Should we get together on a Discord server or something?

**Comment by tomiy** [comment]
This project is kinda already doing that, unless you mean freerider hd?
Anyways, my discord tag is tomiy#2020 if you want to contact me for any questions, a bunch of other guys are also familiar with the code but we can get in touch by proxy as you need more info
